### ISSUE TITLE
Identified Typos

### ISSUE THREAD

**Issue by milesstoetzner** [xlab-si/xopera-docs#12]
Hello, 

I was reading through the docs and identified some typos/ issues. 
I am referring to https://github.com/xlab-si/xopera-docs/blob/790f7f2f177085897572fe5adde9d756a3c91fa0/docs/cli.rst in the following.

- [x] "CLI commands references": "purpose and description" of "opera package" is wrong
- [x] "CLI commands references": "purpose and description" of "opera unpackage" is wrong
- [x] "CLI commands references": the text at the end has a problem: "The commands can be executed in a random order _**and the orchestrator will warn**_ and the orchestrator will warn you in case if any problems. Each CLI command is described more in detail in the following sections."
- [x] "opera deploy" description: "case" should be "care" in "If the number of specified workers is higher than the number of independent nodes, the orchestrator will take _**care**_ of this and will decrease the amount of workers if needed."
- [x] "opera info": missing a word in "print the outputs of the deploy/undeploy _**application.**_"
- [x] "opera info" description: "This **_includes_** printing out the path to TOSCA service template"
- [x] "opera info" description: code block of json example has some problems since the text starting with "xOpera TOSCA orchestration tool is still inside the code box

And a minor one:
- [x] The service template of the CLI Quickstart has some minor differences to the example files. Different default value for `content`, metadata and `content` input has been renamend to `marker`.

Greetings 😄

**Comment by anzoman** [comment]
This has been resolved in bb41479e939e13663420220bb85710129006d92f.

Many thanks @milesstoetzner for discovering all these typos! Feel free to point out if you encounter any more problems.
